version: "2"
services:
 mgruby:
   image: docker.io/yottadb/yottadb-base:latest
   hostname: mgruby
   container_name: mgruby
   networks:
      - yottanet
   ports:
      - 8087:80
   mem_limit: 1G
   volumes:
      - "$PWD/mg_ruby:/home/mg_ruby"
      - "$PWD/global:/home/global"
   entrypoint: /home/mg_ruby/entrypoint.sh


 locust_mgrust:
   image: docker.io/locustio/locust:latest
   networks:
      - yottanet
   ports:
      - 8100:8089
   volumes:
      - "$PWD/locust:/home/locust"
   entrypoint: locust --host 'http://mgruby:80'

networks:
    yottanet:
