[package]
name = "yottatest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yottadb ={ path = "/usr/local/YDBRust" }
rocket = { path = "/usr/local/Rocket/core/lib" }

